"""Added password_hash column to User model

Revision ID: 59486c37e354
Revises: 
Create Date: 2024-04-10 14:23:37.476314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59486c37e354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
